services:
  mariadb:
    image: mariadb
    container_name: mariadb
    env_file: .env
    build: ./requirements/mariadb
    restart: unless-stopped
    networks:
      - intra
    volumes:
      - db-v:/var/lib/mysql

  wordpress:
    image: wordpress
    container_name: wordpress
    env_file: .env
    build: ./requirements/wordpress
    restart: unless-stopped
    volumes:
      - www-v:/var/www
    networks:
      - intra
    depends_on:
      - mariadb
    healthcheck:
        test: ["CMD", "php-fpm7.4", "-t"]
        interval: 10s
        timeout: 5s
        retries: 3

  nginx:
    image: nginx
    container_name: nginx
    env_file: .env
    build: ./requirements/nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - www-v:/var/www
    networks:
      - intra
    depends_on:
       wordpress:
         condition: service_healthy

networks:
  intra:
    driver: bridge

volumes:
  db-v:
    name: db-v
    driver: local
    driver_opts:
      device: '/home/dong-kim/data/db'
      type: 'none'
      o: 'bind'

  www-v:
    name: www-v
    driver: local
    driver_opts:
      device: '/home/dong-kim/data/wordpress'
      type: 'none'
      o: 'bind'